# SVD, LU decompostion, linear equations 


Based on: Geoff Gordon's  [Linear equations](https://qna.cs.cmu.edu/#/pages/view/185)




In [24]:
import numpy as np
from scipy.linalg import lu, eig, svd

In [25]:
A = np.random.normal(size = [5,5])
print(A)

[[-0.29586053  2.01869505 -1.42920101 -1.05873531 -1.07277984]
 [-2.08917931 -0.47351086  0.68873134  0.49182723 -0.47295026]
 [-1.25147599 -1.55659462 -0.94090121 -0.67285734 -0.83878875]
 [ 1.30530375 -0.81994387  2.66056487  0.81706072 -0.03493527]
 [-0.17621399  0.0638752   0.42033988 -0.22447632 -1.39382497]]


In [26]:
U, D, V = np.

L =
[[ 1.          0.          0.          0.          0.        ]
 [ 0.14161567  1.          0.          0.          0.        ]
 [ 0.59902756 -0.61030689  1.          0.          0.        ]
 [-0.62479259 -0.53495821 -0.99513891  1.          0.        ]
 [ 0.08434604  0.04977293 -0.19176837  0.46780502  1.        ]]
U =
[[-2.08917931 -0.47351086  0.68873134  0.49182723 -0.47295026]
 [ 0.          2.0857516  -1.52673616 -1.12838575 -1.00580268]
 [ 0.          0.         -2.28524786 -1.656137   -1.16932681]
 [ 0.          0.          0.         -1.12737487 -2.03213609]
 [ 0.          0.          0.          0.         -0.57746818]]
LU =
[[-2.08917931 -0.47351086  0.68873134  0.49182723 -0.47295026]
 [-0.29586053  2.01869505 -1.42920101 -1.05873531 -1.07277984]
 [-1.25147599 -1.55659462 -0.94090121 -0.67285734 -0.83878875]
 [ 1.30530375 -0.81994387  2.66056487  0.81706072 -0.03493527]
 [-0.17621399  0.0638752   0.42033988 -0.22447632 -1.39382497]]
PA =
[[-2.08917931 -0.47351086  0.68873